/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'dirasti';
  static const String PLUGIN_VERSION = '1.0.4+4';
  static const String ONBOARD_LOGO = 'assets/onboard_logo.png';
  static const String QR_LOGO = 'assets/qr_logo.png';
  static const String SHARE = 'assets/share.png';
}
