/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String CAIRO_VARIABLEFONT_SLNT,
      WGHT = 'Cairo-VariableFont_slnt,wght';
}
